
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - run: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
    - run: nix-build -E 'with import <nixpkgs> {system="aarch64-linux";}; callPackage ./default.nix {}'
    - run: nix-build -E 'with import <nixpkgs> {system="riscv64-linux";}; callPackage ./default.nix {}'

