name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          sandbox-paths = /usr/bin/qemu-riscv64-static /usr/bin/qemu-aarch64-static
          extra-platforms = aarch64-linux riscv64-linux i686-linux
    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Install Software
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static bash

    - run: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
    - run: nix-build -E 'with import <nixpkgs> {system="aarch64-linux";}; callPackage ./default.nix {}'
    - run: nix-build -E 'with import <nixpkgs> {system="riscv64-linux";}; callPackage ./default.nix {}'

